[IDE-13513] feat: add common section for 3d and pending actions doc
intergiro/developer-portal pull request #126
Opened 2022-08-04 13:39 UTC by mmosumgaard

2022-08-04 14:26 UTC, EugeneMakesNoSense approved these changes

2022-08-08 04:02 UTC, silviaulloa approved these changes
Made some minor changes (hopefully I pushed them through correctly) - otherwise all good from my side.

2022-08-10 11:59 UTC, knowakowski-intergiro requested changes

2022-08-10 11:59 UTC, knowakowski-intergiro commented on docs/3d/common/pending-actions.md
> +GET /v3/events/927bf478-e246-477f-b3ef-dfa4b806a640
I would question if we should showcase the approach of retrieving the event here as this is the suboptimal approach to retrieve the pending action. What do you think about doing it the other way around, mention in the sentence the approach with `events` and explain that it requires 1 extra request, while showcasing filtering the pending actions by event id?

2022-08-11 11:43 UTC, mmosumgaard commented on docs/3d/common/pending-actions.md
> +GET /v3/events/927bf478-e246-477f-b3ef-dfa4b806a640
That is a good idea, and the optimal approach is most likely going to be the selected way for clients of accessing pending actions. 

Fixed

2022-08-12 09:27 UTC, knowakowski-intergiro approved these changes

2022-11-25 10:23 UTC, merged