Structuring merchant documents.
Intergiro/developer-portal pull request #16
Opened 2021-07-27 14:45 UTC by marcushanses

Added topup documentation.
Added Card Input documentation.
Added Checkout Documentation.

2021-07-28 09:06 UTC, Magnus93 requested changes

2021-07-28 09:07 UTC, marcushanses commented on docs/merchant/card-input/verfication.md
> +			error =
That doesn't make sense since they are input parameters.

2021-07-28 09:08 UTC, marcushanses commented on docs/merchant/card-input/verfication.md
> +Create an authorization with 3D Secure trying step by step.
Aldready done :)

2021-07-28 09:11 UTC, marcushanses commented on docs/merchant/card-input/verfication.md
> +		<intergiro-card-input class="input"
I used the format given by our lint.

2021-07-28 09:18 UTC, marcushanses commented on docs/merchant/customer/create.md
> +  "customer": <contact information>,
It is not a string so it might be confusing for someone. I think we should use "<something>" for strings, [<something>] for arrays and just <something> for object types.

2021-07-28 09:19 UTC, marcushanses commented on docs/merchant/customer/create.md
> +  "method": [<payment method>],
It is an array so I think the brackets make sense, it is not a string so I don't think quotes make sense.

2021-07-28 09:22 UTC, Magnus93 commented on docs/merchant/card-input/verfication.md
> +			error =
if they are input parameters shouldn't it say:
```js
async function tokenize(card, error) {
...
```

2021-07-28 09:23 UTC, marcushanses commented on docs/merchant/integration-guide/introduction.md
> +| A,P | Verification API          | yes          | Custom UI (optional) | Custom UI (optional) |
This document is not displayed, there is no link to it in the navbar and it is not referenced.

2021-07-28 09:26 UTC, Magnus93 commented on docs/merchant/card-input/verfication.md
> +# Verification
File is called "verfication.md" not "ver**i**fication.md"

2021-07-28 09:29 UTC, marcushanses commented on docs/merchant/integration-guide/introduction.md
> +| A,P | Verification API          | yes          | Custom UI (optional) | Custom UI (optional) |
Maybe it shouldn't be in this pr.

2021-07-28 09:32 UTC, Magnus93 commented on docs/merchant/customer/create.md
> +  "method": [<payment method>],
Maybe writing:
```
"method": <array of payment methods>,
```

2021-07-28 09:35 UTC, marcushanses commented on docs/merchant/card-input/verfication.md
> +			error =
Yes.

2021-07-28 09:41 UTC, Magnus93 commented on docs/merchant/integration-guide/introduction.md
> +| A,P | Verification API          | yes          | Custom UI (optional) | Custom UI (optional) |
ok

2021-08-02 15:02 UTC, robinnedergard requested changes

2021-08-02 16:11 UTC, Magnus93 approved these changes

2021-08-06 11:23 UTC, merged