Postman examples for Card API
Intergiro/developer-portal pull request #21
Opened 2021-08-17 13:18 UTC by nilssonemma

2021-08-20 14:16 UTC, marcushanses approved these changes

2021-08-23 09:10 UTC, Magnus93 commented on docs/.vuepress/public/assets/scripts/card-api-collection.json
> +						"{{baseUrl}}"
The baseUrl can be set for all requests

2021-08-23 09:13 UTC, Magnus93 commented on docs/merchant/card-api/change.md
> +PUT /card/<cardToken>
`v1/card/card_token`

2021-08-23 09:13 UTC, Magnus93 commented on docs/merchant/card-api/fetch.md
> +GET /card/<cardToken>
`v1/card/<card_token>`

2021-08-23 09:18 UTC, Magnus93 requested changes

2021-08-23 09:18 UTC, Magnus93 commented on docs/.vuepress/public/assets/scripts/card-api-collection.json
> +						"{{baseUrl}}"
The baseUrl can be set for all requests

2021-08-23 09:18 UTC, Magnus93 commented on docs/merchant/card-api/fetch.md
> +GET /card/<cardToken>
`v1/card/<card_token>` ?

2021-08-23 09:18 UTC, Magnus93 commented on docs/merchant/card-api/change.md
> +PUT /card/<cardToken>
`v1/card/<card_token>` ?

2021-08-23 09:23 UTC, Magnus93 requested changes

2021-08-23 09:23 UTC, Magnus93 commented on docs/.vuepress/config.js
>        children: [
Also add `"Card API"` to `nav` in config file.

2021-08-25 12:46 UTC, Magnus93 approved these changes

2021-08-25 12:46 UTC, merged