Add Acquring API guide
Intergiro/developer-portal pull request #28
Opened 2021-09-14 13:58 UTC by Magnus93

2021-09-15 14:39 UTC, marcushanses requested changes

2021-09-15 14:39 UTC, marcushanses commented on docs/merchant/integration-guide/acquiring/api.md
> +If you want to avoid handling card information to minimize PCI scope, you can use the [Card Input UI](../../card-input/embed.html#embeddable-component).
... to minimize the PCI scope of your system, ...

2021-09-15 14:39 UTC, marcushanses commented on docs/merchant/integration-guide/acquiring/api.md
> +The Card Input UI can perform 3D-Secure by using the Verification API to perform ([Read more here](../../card-input/verification.html#verification)).
to perform 3D Sercure?

2021-09-15 14:39 UTC, marcushanses commented on docs/merchant/integration-guide/acquiring/api.md
> +It can also be [customized](../../card-input/style.html#styling) to better suit the style of a given website.
Intergiro Card Input can....

2021-09-15 14:39 UTC, marcushanses commented on docs/merchant/integration-guide/acquiring/api.md
> +The Card Input UI can perform 3D-Secure by using the Verification API to perform ([Read more here](../../card-input/verification.html#verification)).
Intergiro Card Input UI...

2021-09-15 14:44 UTC, robinnedergard requested changes
Change datetime section in `docs/merchant/common/reference.md` to 
```
String formated as `"YYYY-MM-DDThh:mm:ss.fffK"`, e.g. `"2020-12-31T23:59:59.999Z"`.
```

2021-09-16 15:19 UTC, nilssonemma approved these changes

2021-09-17 08:21 UTC, marcushanses approved these changes

2021-09-17 10:23 UTC, robinnedergard requested changes

2021-09-17 10:23 UTC, robinnedergard commented on docs/merchant/customer/reference.md
> +In the response from the endpoint an object of the Customer data type will be returned.
```suggestion
In the response from the endpoint, an object of the Customer data type will be returned.
```

2021-09-17 10:23 UTC, robinnedergard commented on docs/merchant/integration-guide/authentication.md
> +Private API-keys are the most potent API-key and let’s you do everything available in the API.
No true in reality, sometimes you have to use customer or public key instead

2021-09-17 10:23 UTC, robinnedergard commented on docs/merchant/integration-guide/authentication.md
> +- customer
Will we mention agent audience to PSP:s?

2021-09-17 10:23 UTC, robinnedergard commented on docs/merchant/integration-guide/authentication.md
> +Private API-keys are the most potent API-key and let’s you do everything available in the API.
Also inconstant use of space after head line

2021-09-20 08:18 UTC, mayask approved these changes

2021-09-20 08:18 UTC, merged