3D flow and verification documention.
Intergiro/developer-portal pull request #29
Opened 2021-09-15 06:58 UTC by marcushanses

2021-09-15 10:01 UTC, Magnus93 requested changes

2021-09-16 11:32 UTC, Magnus93 requested changes

2021-09-16 11:32 UTC, Magnus93 commented on docs/merchant/verification/create.md
> +Example of the details of the verification response with type challenge.
Change to
"... of the \`details\` in the verification ..."

2021-09-17 08:40 UTC, Magnus93 requested changes

2021-09-17 08:40 UTC, Magnus93 commented on docs/merchant/verification/create.md
> +cres=eyJhY3NUcmFuc0lEIjoiODc3OTFjZWUtMjUxNC00MzZjLW
the token can not be easily copied and pasted due to the newlines and tabs. Put everything on one line.

2021-09-17 14:52 UTC, Magnus93 approved these changes

2021-09-20 06:51 UTC, nilssonemma approved these changes

2021-09-20 08:19 UTC, mayask approved these changes

2021-09-20 09:25 UTC, merged