Account Page documentation
Intergiro/developer-portal pull request #4
Opened 2021-06-16 09:12 UTC by nilssonemma

2021-06-16 14:28 UTC, marcushanses requested changes

2021-06-16 14:28 UTC, marcushanses commented on docs/integrate/merchant/account-page.md
> +To integrate the account page to your website, a unique [account key](#account-api-key) is needed for each customer. Account keys are valid for three days until they expire and should thereafter be r
Account keys -> (account key)(account-api-key)s ??

2021-06-16 14:28 UTC, marcushanses commented on docs/integrate/merchant/account-page.md
> +In order to create an Account API key, an account id is needed together with a private key for authorization.
Rewrite?

2021-06-16 14:28 UTC, marcushanses commented on docs/integrate/merchant/account-page.md
> +    "header": {"background": "#fff", "color": "black"},
remove a "}".
Only use RBG.
Double check the colors.

2021-06-16 14:28 UTC, marcushanses commented on docs/integrate/merchant/account-page.md
> +  }'></intergiro-account>
remove a "}".
Only use RBG.
Double check the colors.

2021-06-17 07:28 UTC, robinnedergard requested changes

2021-06-17 07:28 UTC, robinnedergard commented on docs/integrate/merchant/account-page.md
> +Intergiro Account helps you to manage payments for customers with which you have an ongoing relationship. A personal account page is provided to all your customers, to make it easy to update payment
Ongoing relationship?

2021-06-17 07:28 UTC, robinnedergard commented on docs/integrate/merchant/account-page.md
> + The account page can be integrated into your website as an embedded page. The `<intergiro-account>` component can be used to access the entire account page, or to access the single components of the
or to access ~the single~ _individual_ components of the page

2021-06-17 07:28 UTC, robinnedergard commented on docs/integrate/merchant/account-page.md
> +Note: Colors are specified using RGB comma seperated string e.g. "0,0,255" for blue.
~seperated~ _separated_

2021-06-17 07:37 UTC, robinnedergard commented on docs/integrate/merchant/account-page.md
> +Intergiro Account helps you to manage payments for customers with which you have an ongoing relationship. A personal account page is provided to all your customers, to make it easy to update payment
Intergiro Account is a tool for customers to manage payment methods, orders and subscriptions.

2021-06-17 07:38 UTC, robinnedergard commented on docs/integrate/merchant/account-page.md
> +In order to create an Account API key, an account id and a private key is needed.
Depending on the private key used to create the account keys, certain features may be explicitly disabled or enabled.

2021-06-17 08:40 UTC, marcushanses approved these changes

2021-06-17 08:40 UTC, marcushanses commented on docs/integrate/merchant/account-page.md
> +Intergiro Account is a tool for customers to manage payment methods, orders and subscriptions. A personal account page is provided to all your customers, to make it easy to update payment and contact
Intergiro Account is a  personal account page that is provided to all your customers, to make it easy to update payment and contact information, and to provide easy access to all orders associated to the account.

2021-06-17 11:25 UTC, robinnedergard approved these changes

2021-06-17 11:30 UTC, florianebmeier approved these changes

2021-06-17 12:46 UTC, euqen commented on docs/integrate/merchant/account-page.md
> +Host: api.payfunc.com
lets change to merchant.intergiro.com even if it's not available yet

2021-06-17 12:47 UTC, euqen commented on docs/.vuepress/config.js
> +      '/integrate/merchant/': getIntegrateSidebar(),
I guess this is for our merchants not for psps, right? If so please move under /merchant do not keep it under /integrate please

2021-06-21 12:12 UTC, merged