Order and subscription as part of customer create.
intergiro/developer-portal pull request #58
Opened 2021-11-09 14:01 UTC by marcushanses

2021-11-10 15:47 UTC, Magnus93 requested changes

2021-11-10 15:47 UTC, Magnus93 commented on docs/merchant/customer/create.md
> +The response will be a [`Customer`](./reference.html#customer-2) & { order: `tokenized.order` | `tokenized.order`[] } and can be validated
```suggestion
The response will be a [`Customer`](./reference.html#customer-2) & { order: `tokenized.order` | `tokenized.order[]` } and can be validated 
```
More consitent with line 93 (`Subscription Creatable[]`)

2021-11-11 08:18 UTC, nilssonemma requested changes

2021-11-11 08:18 UTC, nilssonemma commented on docs/merchant/customer/create.md
> +To add one or more [`Orders`](../order/reference.html#order) associated with the Customer, populate the `order` field with a list or a single Omit<[`Order.Creatable`](../order/reference.html#creatabl
I think we should avoid writing "Omit" since this is specific for Typescript

2021-11-11 16:12 UTC, nilssonemma commented on docs/merchant/customer/reference.md
> +| `order`        | [`Order | Order[]`](../order/reference.html#creatable)                               | Order or Orders to be created simultaneously as the customer                | Yes      |
Without the payment and customer field

2021-11-15 08:51 UTC, Magnus93 requested changes

2021-11-15 08:51 UTC, Magnus93 commented on docs/merchant/customer/create.md
> +	"items": 42,
Fix indentation

2021-11-15 09:51 UTC, nilssonemma approved these changes

2021-11-15 10:52 UTC, fredrikbryntesson approved these changes

2021-11-15 10:53 UTC, merged