Added missing browser information
intergiro/developer-portal pull request #59
Opened 2021-11-10 14:58 UTC by robinnedergard

2021-11-10 16:12 UTC, Magnus93 requested changes

2021-11-10 16:12 UTC, Magnus93 commented on docs/merchant/customer/payment-methods.md
> +        "colorDepth": 24,
color_depth

2021-11-10 16:13 UTC, Magnus93 requested changes

2021-11-10 16:13 UTC, Magnus93 commented on docs/merchant/order/create.md
> +          "colorDepth": 24,
color_depth

2021-11-10 16:46 UTC, nilssonemma approved these changes

2021-11-10 16:47 UTC, nilssonemma approved these changes

2021-11-11 09:00 UTC, fredrikbryntesson approved these changes

2021-11-11 09:00 UTC, merged