Add Order Reference and Callback documentation
Intergiro/developer-portal pull request #7
Opened 2021-06-23 13:21 UTC by florianebmeier

- [ ] Merge branch `change-account-to-customer` first, then rebase and check links.

2021-06-24 08:11 UTC, Magnus93 approved these changes

2021-06-28 08:24 UTC, Magnus93 requested changes

2021-06-28 08:24 UTC, Magnus93 commented on docs/merchant/integration-guide/balance.md
> +POST https://merchant.intergiro.com/order
Change to: 
```
POST /v1/order

Host: merchant.intergiro.com
Type-Content: application/json
Authentication: ....
```

2021-06-28 08:24 UTC, Magnus93 commented on docs/merchant/integration-guide/balance.md
> +DELETE https://merchant.intergiro.com/customer/<customerId>/balance
Change here as-well
```
DELETE /v1/customer/<customerId>/balance

Host: merchant.intergiro.com

2021-06-28 08:24 UTC, Magnus93 commented on docs/merchant/integration-guide/change-contact-information.md
> +PUT /customer/<customerId>/contact
Add `/v1/customer/...`, `Host` and `Content-Type`

And add this to all other API calls
(`Content-Type: application/json` is only neccesery when sending a JSON)

2021-06-28 08:49 UTC, marcushanses requested changes

2021-06-28 08:49 UTC, marcushanses commented on docs/merchant/reference/order.md
> +| `currency` | [`Currency`](../../integrate/acquiring/reference#currency)           |                                                            |          |
Add category.

2021-06-28 08:53 UTC, marcushanses requested changes

2021-06-28 08:53 UTC, marcushanses commented on docs/merchant/reference/callback.md
> +When creating an [`order`](./reference/order) you can provide a callback url under the field [`callback`]().
Fix the link.

2021-06-28 11:06 UTC, marcushanses approved these changes

2021-07-01 07:23 UTC, Magnus93 approved these changes

2021-07-05 15:14 UTC, Magnus93 commented
Rebase
Also let README file function be called `mounted`, not `created`

2021-07-06 15:52 UTC, merged