Change Account to Customer
Intergiro/developer-portal pull request #8
Opened 2021-06-24 07:55 UTC by Magnus93

Add integration guide with customer registration

2021-06-25 11:49 UTC, euqen commented on docs/merchant/integration-guide/create-customer-api-key.md
> +POST https://api.payfunc.com/customer/<customerId>
please change to merchant.intergiro.com

2021-06-25 11:50 UTC, euqen commented on docs/merchant/customer-page.md
> +POST /v1/customer/<customerId>
in some endpoints below you don't have versioning in the url. Is this relevant here?

2021-06-25 11:54 UTC, euqen commented on docs/merchant/integration-guide/customer-registration.md
> +	<script src="https://api.payfunc.com/ui/onboard/payfunc-onboard.js"></script>
please change this domain name

2021-06-25 11:55 UTC, euqen commented on docs/merchant/integration-guide/customer-registration.md
> +	<link href="https://theme.payfunc.com/light/index.css" rel="stylesheet">
https:/cdn.merchant.intergiro.com/themes/light/index.css

2021-06-25 11:57 UTC, euqen commented on docs/merchant/integration-guide/list-customers.md
> +    "id": "<PayFunc customer identifier>",
please make sure you are not using payfunc anywhere

2021-06-25 11:58 UTC, euqen commented
good job!

2021-06-28 07:03 UTC, Magnus93 commented on docs/merchant/customer-page.md
> +POST /v1/customer/<customerId>
All URL's should have versioning, I've fixed it now.

2021-06-28 07:07 UTC, Magnus93 commented on docs/merchant/integration-guide/list-customers.md
> +    "id": "<PayFunc customer identifier>",
I've removed all mentions of payfunc except for:
https://github.com/Intergiro/developer-portal/pull/8/files#diff-24716df81deb9767eb9dc85398e37223b96854271aa6254aa34ef80ec4b35fb1R31

Since this is a link to some example source code.

2021-06-28 07:26 UTC, nilssonemma requested changes

2021-06-28 07:26 UTC, nilssonemma commented on docs/merchant/integration-guide/balance.md
> +Adding funds to the balance can be done via the regular **Order Endpoint ???**.
Should be a link to the order endpoint

2021-06-28 07:26 UTC, nilssonemma commented on docs/merchant/integration-guide/create-customer.md
> +<!-- Part of the reponse
Can these comments be removed?

2021-06-28 07:26 UTC, nilssonemma commented on docs/merchant/integration-guide/patch-customer.md
> +<!-- In any case, calling this endpoint will fix deprecated customers with invalid balance configurations and due dates. -->
Can this comment be removed?

2021-06-28 09:55 UTC, florianebmeier requested changes

2021-06-28 09:55 UTC, florianebmeier commented on docs/merchant/integration-guide/create-customer-order.md
> +The requirements for the order is that the customer id is set and that `payment` is set to `{ "type": "customer" }`.
The  customer field in the creatable has to be set to the customer id. 
The payment field has to be a Customer Payment Creatable, then link to the correct field in the reference(../reference/payment.html#customer-payment-creatable)

2021-06-30 15:06 UTC, florianebmeier requested changes

2021-06-30 15:06 UTC, florianebmeier commented on docs/merchant/integration-guide/create-customer-order.md
> +the `customer` field must be set to an customer id and the `payment` field must be a [Customer Payment Creatable](../reference/payment.html#customer-payment-creatable).
must be set to ~~an~~ a customer id

2021-06-30 15:06 UTC, florianebmeier commented on docs/merchant/integration-guide/create-customer-order.md
> +    "customer": "<id of customer or contact infromation>",
infromation

2021-06-30 15:13 UTC, florianebmeier approved these changes

2021-07-01 07:00 UTC, nilssonemma approved these changes

2021-07-06 15:51 UTC, merged