Documentation about passing ID in all 3D steps
intergiro/developer-portal pull request #84
Opened 2022-02-10 12:29 UTC by nilssonemma

2022-02-10 12:52 UTC, Magnus93 requested changes

2022-02-10 12:52 UTC, Magnus93 commented on docs/merchant/order/create.md
> +**Note: Include the `id` from the error response in the request body for all following calls to the order-create endpoint, concerning the same order.** This is important to keep a correct [History](.
We write `3DS`(all uppercase) in most of the text.
```suggestion
**Note: Include the `id` from the error response in the request body for all following calls to the order-create endpoint, concerning the same order.** This is important to keep a correct [History](../authorization/reference.html#history) of the authorization creation, and to make sure 3DS is done correctly. The id field in an Order Creatable should never be populated with any id other than the id received from the order endpoint.
```

2022-02-14 08:20 UTC, marcushanses approved these changes

2022-02-14 14:19 UTC, fredrikbryntesson approved these changes

2022-02-14 14:19 UTC, merged